apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: busybox
        image: busybox
        command: ['sleep', '30']
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
   
