apiVersion: v1
kind: Secret
metadata:
  name: ssl-secret
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQwVENDQXJtZ0F3SUJBZ0lVTEtlaHF4SVhE
    ZEVyZ0hySE4yVERMQ3pMMnhjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2VERUxNQWtHQTFVRUJoTUNV
    bFV4RERBS0JnTlZCQWdNQTBsU1N6RVFNQTRHQTFVRUJ3d0hTWEpyZFhSegphekVRTUE0R0ExVUVD
    Z3dIUlZoQlRWQk1SVEVMTUFrR0ExVUVDd3dDVFZreEZEQVNCZ05WQkFNTUMyVjRZVzF3CmJHVXVZ
    Mjl0TVJRd0VnWUpLb1pJaHZjTkFRa0JGZ1ZoUUdFdVlUQWVGdzB5TXpFd01URXhORFV5TkRoYUZ3
    MHkKTkRFd01UQXhORFV5TkRoYU1IZ3hDekFKQmdOVkJBWVRBbEpWTVF3d0NnWURWUVFJREFOSlVr
    c3hFREFPQmdOVgpCQWNNQjBseWEzVjBjMnN4RURBT0JnTlZCQW9NQjBWWVFVMVFURVV4Q3pBSkJn
    TlZCQXNNQWsxWk1SUXdFZ1lEClZRUUREQXRsZUdGdGNHeGxMbU52YlRFVU1CSUdDU3FHU0liM0RR
    RUpBUllGWVVCaExtRXdnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFR
    Q2I3SGQxakM1bnBRc1RNcHhvdHh3YWZrYlZNTGl5SW03TwpBU0VpamVZM1U1N2hDMXpZRld3eHRI
    TWhvdVNhUVRXNTJKVXJsdE9Fbm0zY2JKU3VhTkRMdWpQWXArd3dKZmN1Ck9Mamx0cnh2UG9JSDRC
    WG1CM0txOTdWRTFEUENCam9WaTlxY08vUWxLWThzRXZKd2c4N2RWTHRFL1RGSVlEZHIKeDk2ZHVP
    NytZRVBuSE92NnlYRVJ5NmIzWGpyNmJlR0FiYzBRc3JWMEQ1TDJHdTkwdDFBdDBOUTNZMmFEY2dD
    bgpmeE9OMm1aNVNQaEVMeW94OS82a1NHaWxOeUt3VmNGb3RNOWxvdHJQSFMvVkxlZkxEd1U3eUlE
    V1BuZUI5NHZlCnJTQ05PVzZPNHFjN0tOQXBxTWswSTVxTkJFeUxWYmxrWjhrTTVSQm5uRjB5T1JS
    dEN4WjNBZ01CQUFHalV6QlIKTUIwR0ExVWREZ1FXQkJSVW5OaUg4R240Zzl6SWdTTmdkRHFaNU44
    dG9EQWZCZ05WSFNNRUdEQVdnQlJVbk5pSAo4R240Zzl6SWdTTmdkRHFaNU44dG9EQVBCZ05WSFJN
    QkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBCkE0SUJBUUJvU2YyaExKSnhrQmVmMG45
    NWY4b3NudllVRFp0S0dwNkF3UENoNENUYWdvVHJrbHQ5bVdSSUpYYkcKL1U3V2p5VjloVnZQUEFi
    KzBkcmR6NmhlV01ZaUFvSEtydXhGeW1OczZiQmFNZFZ3MEJPdzZiSUdDR0pRU25GRAorbGFhRVR6
    ay9TSWkvNFJKN2krU1Y1ODF5TjdPWWVaZDVaVHJ4SEFUcjBFbGF1MHB6Zy9zN2E0dG50WklRTEMv
    CjY4cWgybGduR01QTTk2WHE3b2hxSVIyOTZIbXd5bk8rekY5czFlcjN6UG0wTFhYenlGaGxHU0Fq
    WWlmRUZWVkcKN3g3MzVEcjNVTEhTd1JqWWdSNnZQZ3NLYm1GZXlhZUl1YmZ1ZTBRd1hCWUtZVVFO
    bG5aaUdHTldvSDJkRDh3OApVSXhUVlhZUVRqUHkzMHJzRDhmUmpQUWV5c0daCi0tLS0tRU5EIENF
    UlRJRklDQVRFLS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2I3SGQxakM1bnBRc1QKTXB4b3R4d2Fma2JWTUxpeUltN09B
    U0VpamVZM1U1N2hDMXpZRld3eHRITWhvdVNhUVRXNTJKVXJsdE9Fbm0zYwpiSlN1YU5ETHVqUFlw
    K3d3SmZjdU9Mamx0cnh2UG9JSDRCWG1CM0txOTdWRTFEUENCam9WaTlxY08vUWxLWThzCkV2Sndn
    ODdkVkx0RS9URklZRGRyeDk2ZHVPNytZRVBuSE92NnlYRVJ5NmIzWGpyNmJlR0FiYzBRc3JWMEQ1
    TDIKR3U5MHQxQXQwTlEzWTJhRGNnQ25meE9OMm1aNVNQaEVMeW94OS82a1NHaWxOeUt3VmNGb3RN
    OWxvdHJQSFMvVgpMZWZMRHdVN3lJRFdQbmVCOTR2ZXJTQ05PVzZPNHFjN0tOQXBxTWswSTVxTkJF
    eUxWYmxrWjhrTTVSQm5uRjB5Ck9SUnRDeFozQWdNQkFBRUNnZ0VBS3pBWnZJalo5NkpLeVlQOHQ3
    SjBTZEJOUFZLejdiOUUwckdVWkhaS1hHdkEKZDVRR29PRjZLT0JTL1crWmd6SnB0N0xLU3BzSnRs
    T05tWDdIeGZGSldBeVl2THR5VzduQVYrQ2xNaGRsNVNnNgpxd1RCL0FkM0Z1enFuQWhzMTZLUzV4
    SG9PTnNRV2xUREQ5R2xyazJMK0ZrMlQ3c1RzZmpZa1BWNDcxWGdlTHR4CmVWVlZYa1AwaElJLzd6
    M3E1YTlZTjE5S3ZGNTJYWUdJWThtUlJMQTQ1NWtrd3R6UGpWVFFmMFFrRXRuYXAwN1YKaWp5dGxa
    M0lKdmszeTkrNjV4RzBJL3BJYWtkalV3N2tsQStCVEVoTUdEMEs3MWs3Wnc0Q29CY0oxY044Y0J4
    awpwN1RzL3hsTVBzRnRmOG9mQVZiQmkvVFlrT0JLOThXV1V4aVNkTitNY1FLQmdRRFE4Zm1jdXV2
    T1JWTFd0KzMzCklWOEhGRXBqeDA5bTliWHAveTlYWGpQUXRqWXE5R2dnaFp4dkpTTmg5c3MwL2tP
    V29sUzFoZ05CTmpidUJzYzcKdGptNGpWOU1XNkV0cWh3elpjZGx0TlFTN0wzRUxIMWZvd2xyUS9i
    aUV6aEkyVHFKazJLRFZ1RmhSYUdpUlVSSApkWDZQbVEzZm85Sm9RdThNcksrVFlvbmowUUtCZ1FD
    L0NiZHZVeVBBTWthZGxYWFZhamllcit4TDFuOUU0RDBoCnMxeVpPOVJqMGtHQmNVWFVLTVdkRW9P
    eXlmYldlU2pkc3ptUFlwd0xSZ0xpeVpraWdCeThuV09KM3ZtTlBPUU4KYUpFRUMrMUhCRENRcTgr
    WUtNOEIwdDNmc2VITzVFb3dGaFA3YjZPNmJwUk13S3dkNHJORUwwTjdKU0M3eVpmNwpsNk95L0pY
    UHh3S0JnQk9VS1B5YnMwN2Z4aFJpcGNTN2Rza1dDS1p5M2FqYksxR2kzTS9GL3ZyMnAvcThiaWxs
    Cis3T2Fla2RLdGQzZ1dYcjYrUThOWUs2eW90RUpCNUE3MGdyT0RIaitPUXNyWG5zZWRXRzlZUVhv
    OHhzM3hBTzcKSmozTDM0MXRtWitSNDE5UzFTOVRhOGtPbWtlM1Q5K1dUZWFzdzlVSjU4Um5TVGta
    MFZYeExOU1JBb0dBYTh4YQoweG5TQWFFZEVjMEZ5ZUIvaEtQMnJiQ2k3a1d1bVRheDJOSFcvbURs
    ajlwUU1mQ3oyZmRaazJpOXZiWnVwZk45ClZuaXBYdjhwbjdsc2pQaEh2dkw4K1E1Mk9RbVVFakRn
    SzYxalBnQ1NPd0NJU3U4MEtHNUp2dkdNWHdlWkNWdGIKK1RTODZmVjkvM1YxYWdQRGJvVlJDY3Nn
    bG5haUtWa2ZDVi9ZVlg4Q2dZRUFuZDlEREZodEJ4RU9mV1Y0RWdIQgpqUWZaMDZ0RXl5elh5T2oz
    dXpXWXp4ZTQxUnZ6azBaYWZmeEpnaGtNUEhMa0FRU0RHRzk1ODNXdWlIQ3N2bGM1Ck1taEIzRTRq
    RVU5TFR0OXNiMmVvR0FmNERCZEdhcHp6VEgvNDhvMDlGaHAwUmJ5eFcvVXIyZEpvNU5sN2pIaW4K
    UkZOaDdMRDQ2dXVMWS8wRUhRSmRhWjA9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
type: kubernetes.io/tls