apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-pod
  labels:
    app: vol1
spec:
      selector:
        matchLabels:
          app: vol1
      template:
        metadata:
          labels:
            app: vol1
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ['sh','-c','while true; do date >> /output/some_file.txt; sleep 5; done']
            volumeMounts:
            - name: task-pv-storage
              mountPath: /output
          - name: multitool
            image: wbitt/network-multitool
            volumeMounts:
            - name: task-pv-storage
              mountPath: /input
          volumes:
          - name: task-pv-storage
            persistentVolumeClaim:
              claimName: task-pv-claim